stages:
  - test

sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`
env:
  matrix:
    # - INSTANCE: default-debian-9-2019-2-py3
    # TODO: Re-enable this once the `systemd` service can be restarted reliably
    # - INSTANCE: default-ubuntu-1804-2019-2-py3
    - INSTANCE: default-centos-7-2019-2-py3
    # - INSTANCE: default-fedora-29-2019-2-py3
    # - INSTANCE: default-opensuse-leap-15-2019-2-py3
    # - INSTANCE: default-debian-9-2018-3-py2
    # - INSTANCE: default-ubuntu-1604-2018-3-py2
    # - INSTANCE: default-centos-7-2018-3-py2
    # - INSTANCE: default-fedora-29-2018-3-py2
    # TODO: Use this when fixed instead of `opensuse-423`
    # NOTE: Having to temporarily disable `opensuse-423` due to slow mirror
    # - INSTANCE: default-opensuse-leap-15-2018-3-py2
    # - INSTANCE: default-opensuse-423-2018-3-py2
    # - INSTANCE: default-debian-8-2017-7-py2
    # - INSTANCE: default-ubuntu-1604-2017-7-py2
    # - INSTANCE: default-centos-6-2017-7-py2
    # - INSTANCE: default-fedora-28-2017-7-py2
    # - INSTANCE: default-opensuse-leap-42-2017-7-py2

script:
  - bundle exec kitchen verify ${INSTANCE}
